apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-1
managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      'f:spec':
        'f:replicas': {}
    manager: kubectl
    operation: Update
    subresource: scale
    apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      'f:metadata':
        'f:labels': {}

